### ISSUE TITLE
No changes detected in GitHub actions

### ISSUE THREAD

**Issue by NickSevens** [microsoft/beachball#420]
I'm setting up beachball in a github action PR trigger. But, no changes are ever detected when pushing a commit to the PR.
If I run `beachball change` locally the changes _are_ detected as should.

Can anyone point me in the direction of what I'm doing wrong?

The github action file looks like this:

```
name: CR validation

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: yarn

      - name: Check
        run: yarn checkchange
```

Thanks in advance
